export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Main Entities",
    "editor.solar_section": "Solar",
    "editor.grid_section": "Grid Connection",
    "editor.battery_section": "Battery",
    "editor.consumers_section": "Additional Consumers",
    "editor.options_section": "Appearance & Options",
    "editor.flow_rate_title": "Show Flow Rates (W) on pipes",
    "editor.invert_battery": "Invert Power Value (+/-)",
    "editor.label_toggle": "Show Label in Bubble",
    "editor.compact_view": "Compact View (evcc)",
    "editor.compact_details": "Compact View Details",
    "editor.hide_inactive": "Hide Inactive Pipes",
    "editor.entity": "Combined Battery Sensor (W)",
    "editor.label": "Label",
    "editor.icon": "Icon",
    "editor.back": "Back",
    "editor.battery_soc_label": "State of Charge (%)",
    "editor.house_total_title": "🏠 Total Consumption (optional)",
    "editor.house_sensor_label": "Sensor for House Consumption (optional)",
    "editor.house_sensor_hint": "Required to make the house icon clickable (more-details). Otherwise, the house consumption is calculated.",
    "editor.consumer_1_title": "🚗 Left (Purple)",
    "editor.consumer_2_title": "♨️ Center (Orange)",
    "editor.consumer_3_title": "🏊 Right (Cyan)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/House)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Tinted Background in Bubbles",
    "editor.colored_values": "Colored Text Values",
    "editor.hide_consumer_icons": "Hide Consumer Icons",
    "editor.invert_consumer_1": "Invert Sensor Value (+/-)",
    "editor.secondary_sensor": "Secondary Sensor (display only)",
    "editor.grid_to_battery_sensor": "Grid to Battery Sensor (W, optional)",
    "editor.grid_to_battery_hint": "Optional: separate sensor for grid-to-battery flow. If empty, the value is calculated automatically.",
    "editor.grid_combined_sensor": "Combined Grid Sensor (W, Optional)",
    "editor.grid_combined_hint": "Single sensor for import AND export: positive = import, negative = export. Overrides combined import/export sensor.",
    "editor.color_picker": "Bubble Color",
    "editor.pipe_color": "Pipe Color",
    "editor.export_color": "Export Color",
    "editor.consumer_unit_kw": "Sensor reports in kW",
    "editor.show_consumer_always": "Show Consumers at zero watts",
    "editor.battery_charge_sensor": "Battery Charge Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Battery Discharge Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.consumer_1_hide_pipe": "Hide pipe at low power",
    "editor.consumer_pipe_threshold": "Pipe Threshold (Watts)",
    "editor.text_color": "Text Color",
    "editor.icon_color": "Icon Color",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Battery charge via house consumption",
    "editor.battery_show_power": "Show power instead of SoC",
    "editor.solar_unit_kw": "Show Solar in kW",
    "editor.grid_unit_kw": "Show Grid in kW",
    "editor.battery_unit_kw": "Show Battery in kW",
    "editor.consumer_4_title": "⚡ Row 2 Left (Yellow)",
    "editor.consumer_5_title": "💡 Row 2 Right (Indigo)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Grid",
    "card.label_battery": "Battery",
    "card.label_house": "Consumption",
    "card.label_car": "Car",
    "card.label_heater": "Heater",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Cons. 4",
    "card.label_consumer_5": "Cons. 5",
  }
};
